### ISSUE TITLE
Add placing flags on mines

### ISSUE THREAD

**Issue by DarkGuy10** [DarkKnight450/minesweeper#1]
Dont you have to place flags on the mines too tho?

**Comment by BillyDoesDev** [comment]
Yeah, kept that for later tbh
I'll add it later in the future probably

**Comment by BillyDoesDev** [comment]
> Dont you have to place flags on the mines too tho?

Alright, I've added flags now
There's no fancy stuff going on tho.. just flagging and unflagging

**Comment by DarkGuy10** [comment]
> Alright, I've added flags now There's no fancy stuff going on tho.. just flagging and unflagging

:0 that was quick
